//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Document.Management.System.DataAccess.SQLDB.Models
{
    using global::System.Data.Entity;
    using global::System.Data.Entity.Infrastructure;
    using System;
    
    public partial class DocumentManagementDBEntities : DbContext
    {
        public DocumentManagementDBEntities()
            : base("name=DocumentManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document> Documents { get; set; }
    }
}
