//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Document.Management.System.DataAccess.SQLDB.Models
{
    public partial class Document
    {
        public int ID { get; set; }
        public Nullable<DateTime> UploadDate { get; set; }
        public Nullable<DateTime> LastAccessedDate { get; set; }
        public string LastAccessedUser { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileName { get; set; }
        public string FilePhysicalName { get; set; }
    }
}
